hypertrace/config-service

.github/workflows/pr-build.yml
.github/workflows/pr-test.yml
config-service-api/build.gradle.kts
config-service-impl/build.gradle.kts
config-service/build.gradle.kts

Updating snyk to fix vulnerabilities after registering projects. Also updated buf and fixed url format.

chore: fix snyk update and fix buf

---

README.md

This PR, 
- Updated architecture diagram for query layer architecture in README
- Added details of config service and testing steps
NA
- https://docs.hypertrace.org/arch/

docs: updates architecture diagram and added details in README

---

config-proto-converter/build.gradle.kts
config-service-api/build.gradle.kts
config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/ConfigServiceUtils.java
config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/MockGenericConfigService.java
config-service/build.gradle.kts
spaces-config-service-impl/build.gradle.kts
spaces-config-service-impl/src/test/java/org/hypertrace/space/config/service/SpacesConfigServiceImplTest.java

Publish proto-converter and config-service which modules

Publish proto convereter and config-service

---

config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto
config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/MockGenericConfigService.java
config-service-impl/build.gradle.kts
config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java
config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigStore.java
config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java
config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java
config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java
config-service/build.gradle.kts

Extension of https://github.com/hypertrace/config-service/issues/25
Updated unit tests

Expose creation and update timestamp in UpsertConfigResponse

---

config-proto-converter/build.gradle.kts
config-service-api/build.gradle.kts
config-service/build.gradle.kts
spaces-config-service-api/build.gradle.kts

chore(deps): upgrade grpc

---

.snyk
config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto
config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java
config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java
config-service/src/integrationTest/java/org/hypertrace/config/service/ConfigServiceIntegrationTest.java

Added DEFAULT_CONTEXT as default when context is empty to delete corresponding config

Added support for empty context in delete API

---

.github/workflows/pr-test.yml
gradle/libs.versions.toml

Change kafka version to match other kafka client versions in use throughout platform

chore: fix kafka version to match platform

---

label-application-rule-config-service-api/src/main/proto/org/hypertrace/label/application/rule/config/service/v1/label_application_rule.proto
label-application-rule-config-service-impl/src/main/java/org/hypertrace/label/application/rule/config/service/LabelApplicationRuleValidatorImpl.java
label-application-rule-config-service-impl/src/test/java/org/hypertrace/label/application/rule/config/service/LabelApplicationRuleConfigServiceImplTest.java
label-application-rule-config-service-impl/src/test/java/org/hypertrace/label/application/rule/config/service/LabelApplicationRuleValidatorTest.java

Changed label application rule to support multiple labels and entity-types and single dynamic label

---

config-service-change-event-generator/build.gradle.kts
config-service/build.gradle.kts
gradle/libs.versions.toml

Pin a couple flagged transitive libs with vulnerabilities

fix: update vulnerable libs

---

gradle/libs.versions.toml

fix: update vulnerable log4j

---

gradle/libs.versions.toml

chore: update netty

---

gradle/libs.versions.toml

chore: update log4j version to 2.17.0

---

span-processing-config-service-api/src/main/proto/org/hypertrace/span/processing/config/service/v1/span_filter.proto
span-processing-config-service-api/src/main/proto/org/hypertrace/span/processing/config/service/v1/span_processing_config_service.proto

add api naming rules apis

---

.snyk
config-service-change-event-generator/build.gradle.kts
config-service/build.gradle.kts
gradle/libs.versions.toml
object-store/src/main/java/org/hypertrace/config/objectstore/IdentifiedObjectStore.java

Println got checked in and apparently not noticed for months...

fix: remove extra println

---

gradle/libs.versions.toml

Netty vulnerability detected by snyk fixed in dependent PR https://github.com/hypertrace/java-grpc-utils/pull/28

chore: update grpc utils to fix netty vulnerability

---

alerting-config-service-api/build.gradle.kts
alerting-config-service-impl/build.gradle.kts
build.gradle.kts
label-application-rule-config-service-api/build.gradle.kts
label-application-rule-config-service-impl/build.gradle.kts
labels-config-service-api/build.gradle.kts
labels-config-service-impl/build.gradle.kts
notification-channel-config-service-api/build.gradle.kts
notification-channel-config-service-impl/build.gradle.kts
notification-rule-config-service-api/build.gradle.kts
notification-rule-config-service-impl/build.gradle.kts
span-processing-config-service-impl/build.gradle.kts

style: update style plugin and format

---

notification-channel-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceImpl.java
notification-channel-config-service-impl/src/test/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceImplTest.java

Reverts hypertrace/config-service#137
Reverting based on discussions here https://github.com/Traceableai/graphql-service/pull/1100#discussion_r965439151

Revert "Populated id in create and update channel request"

---

gradle/libs.versions.toml

fix-vulnerabilities

---

gradle/libs.versions.toml

Upgraded the protobuf-java-util version to remove the vulnerabilites

fixed vulnerabilitiy

---

notification-channel-config-service-api/src/main/proto/org/hypertrace/notification/config/service/v1/notification_channel.proto
notification-channel-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceRequestValidator.java

Added splunk webhook support in channel config

ENG-28667: Added splunk webhook support

---

label-application-rule-config-service-api/src/main/proto/org/hypertrace/label/application/rule/config/service/v1/label_application_rule.proto

Added new operator to check IP within range

---

span-processing-utils/src/main/java/org/hypertrace/config/span/processing/utils/SpanFilterMatcher.java
span-processing-utils/src/test/java/org/hypertrace/config/span/processing/utils/SpanFilterMatcherTest.java

Added try-catch to validate the regex passed to matches in SpanFilterMatcher

---

span-processing-config-service-impl/build.gradle.kts
span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/validation/SpanProcessingConfigRequestValidator.java
span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/validation/SpanProcessingRequestValidatorTest.java
span-processing-utils/src/main/java/org/hypertrace/config/span/processing/utils/SpanFilterMatcher.java
span-processing-utils/src/test/java/org/hypertrace/config/span/processing/utils/SpanFilterMatcherTest.java

Added validation for regex passed

---

config-service-factory/src/main/java/org/hypertrace/config/service/ConfigServiceFactory.java
span-processing-config-service-impl/build.gradle.kts
span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceFactory.java
span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceModule.java
span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/store/ExcludeSpanRulesConfigStore.java
span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceImplTest.java
span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceModuleTest.java

This PR adds config change event publishing support for Exclude span rules

chore: config change event publishing support for exclude span rules

---

notification-channel-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceRequestValidator.java
notification-channel-config-service-impl/src/test/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceRequestValidatorTest.java

Https validation for webhook notification channels is added.  It is missed in update flow although added in create flow. 
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally.

Https validation for Notification channel webhooks

---

owasp-suppressions.xml

Add temp suppression, remove old temp suppressions.

chore: update suppressions

---

span-processing-config-service-api/src/main/proto/org/hypertrace/span/processing/config/service/v1/span_processing_config_service.proto

chore | Proto changes for adding evaluation targets for each exclude span rule

---

notification-rule-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceImpl.java
notification-rule-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceRequestValidator.java
notification-rule-config-service-impl/src/test/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceImplTest.java

Validation that Multiple Rules with Same Name cannot be Created

---

notification-rule-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceRequestValidator.java

Fix rule name duplication check in update
