hypertrace/config-service

config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto, config-service-impl/build.gradle.kts, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceUtils.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigStore.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceUtilsTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/TestUtils.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java, config-service/src/integrationTest/java/org/hypertrace/config/service/ConfigServiceIntegrationTest.java, helm/values.yaml
- Add API for getting all configs (i.e. across all the contexts) for the specified request
- Add API for deleting the config for the specified request
- Update semantics of upsert config API - It should merge the specified config with the existing config and upsert the resulting config into the store. Also it should return the config which is upserted.
Added and updated unit tests and integration tests for the changes made.
=> Add APIs for deleteConfig and getAllConfigs and modify semantics of upsertConfig

.gitignore, buf.yaml, config-proto-converter/build.gradle.kts, config-proto-converter/src/main/java/org/hypertrace/config/proto/converter/ConfigProtoConverter.java, config-service-api/build.gradle.kts, config-service/build.gradle.kts, config-service/src/main/java/org/hypertrace/config/service/ConfigService.java, config-service/src/main/resources/configs/config-service/application.conf, config-service/src/testFixtures/java/org/hypertrace/config/service/MockGenericConfigService.java, settings.gradle.kts, spaces-config-service-api/build.gradle.kts, spaces-config-service-api/src/main/proto/org/hypertrace/spaces/config/service/v1/space_config_rule.proto, spaces-config-service-api/src/main/proto/org/hypertrace/spaces/config/service/v1/spaces_config_service.proto, spaces-config-service-impl/build.gradle.kts, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRequestConverter.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRequestConverterImpl.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRequestValidator.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRequestValidatorImpl.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigResponseConverter.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigResponseConverterImpl.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRuleConverter.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRuleConverterImpl.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpaceConfigRuleIdGenerator.java, spaces-config-service-impl/src/main/java/org/hypertrace/space/config/service/SpacesConfigServiceImpl.java, spaces-config-service-impl/src/test/java/org/hypertrace/space/config/service/SpaceConfigRequestConverterImplTest.java, spaces-config-service-impl/src/test/java/org/hypertrace/space/config/service/SpaceConfigRequestValidatorImplTest.java, spaces-config-service-impl/src/test/java/org/hypertrace/space/config/service/SpaceConfigResponseConverterImplTest.java, spaces-config-service-impl/src/test/java/org/hypertrace/space/config/service/SpaceConfigRuleConverterImplTest.java, spaces-config-service-impl/src/test/java/org/hypertrace/space/config/service/SpacesConfigServiceImplTest.java
Spaces config service allows for managing space configuration rules to be evaluated during the ingestion pipeline in the SpaceEnricher, and is used as part of hypertrace/hypertrace#142 . Management of these rules will be exposed externally via graphql.
By the time the tests were written on this one, the PR got pretty large - although not a significant amount of logic. If it makes the review easier, I can split a few things up.
=> feat: add spaces config service

config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java
The listCollection api returns the list of tables prefix with db name.
```
INFO  o.h.c.s.s.DocumentConfigStore - list of collections:[default_db.attribute_metadata, default_db.config_bootstrap_status, default_db.configurations, default_db.entity_types, default_db.entity_type_relations]
```
So, the method `getOrCreateCollection` was failing on postgres collection side if a table already exists.
```
postgres                | 2021-02-01 08:16:20.136 UTC [76] ERROR:  relation "configurations" already exists
```
Currently, there is an assumption on dbname (`default_db`) while using mongo as docstore, we will have to fix that first. For now, 
We don't have to explicitly check if the collection exists while using `mongo` as docstore. On postgres side, it has been taken care of inside …
=> fixing an initialisation issue when using postgres as docstore

.snyk, config-service/src/testFixtures/java/org/hypertrace/config/service/MockGenericConfigService.java
Update mock config service to handle case of default context on read, write and delete.
=> test: update mock generic config service to support default

config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, config-service/src/integrationTest/java/org/hypertrace/config/service/ConfigServiceIntegrationTest.java
This change was needed to support the update of the fields with default proto value. We can't distinguish if the default value was being set(updated) or it's just the default proto value.
eg: If a flag  in config is marked as true, now we want to update it to false, it's not possible with the current merging/partial update logic. So, for now, support is for full update of the config.
=> Upsert overriding with the new config to be upserted

config-service-impl/build.gradle.kts
Updates doc-store version to include SQLi fix - hypertrace/document-store#30
=> chore: bump doc-store version to include SQLi fix

config-service-impl/build.gradle.kts, config-service/build.gradle.kts
Updates doc-store version to include postgres impl of exists, not-exists, and NEQ filters
- hypertrace/document-store#35
- hypertrace/document-store#33
=> chore: bump doc-store version to include postgres impl of exits, not-exits and neq

config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceUtils.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigDocument.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigStore.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/ConfigDocumentTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java, config-service-impl/src/test/resources/config1.json, config-service/src/integrationTest/java/org/hypertrace/config/service/ConfigServiceIntegrationTest.java
Addresses https://github.com/hypertrace/config-service/issues/25
Unit tests and integration tests
=> Expose creation and update timestamp in getAllConfigs API

config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigDocument.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/ConfigDocumentTest.java
Fixes https://github.com/hypertrace/config-service/issues/16
Serialization of `NULL_VALUE` (`Value.newBuilder().setNullValue(NullValue.NULL_VALUE).build()`) yields the string - "null", which when deserialized was previously returning the Value as `null`. Although, we handle `null` also using the [isNull() method](https://github.com/hypertrace/config-service/blob/main/config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceUtils.java#L73) (which is why it wasn't affecting the client), we also log an error saying that it is unexpected because ideally, we shouldn't be working with `null` - instead we should be using the null placeholder - `NULL_VALUE`.
So, this change tells the `JsonDeserializer` to use the null placeholder (`NULL_VALUE`) on encountering the string - …
=> Fixes #16 : Handle null values gracefully

config-proto-converter/build.gradle.kts, config-service-api/build.gradle.kts, config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/MockGenericConfigService.java, config-service-impl/build.gradle.kts, config-service/build.gradle.kts, spaces-config-service-api/build.gradle.kts, spaces-config-service-impl/build.gradle.kts
When using inline mocks, we want to use the real bind service in our mock config service. Also bumped some services.
=> fix: update mock generic config service

labels-config-service-impl/src/main/java/org/hypertrace/label/config/service/LabelsConfigServiceImpl.java, labels-config-service-impl/src/test/java/org/hypertrace/label/config/service/LabelsConfigServiceImplTest.java
**Enforcing Key uniqueness for labels:** Added support for checking duplicate keys while creating or updated labels. Added unit tests to verify correctness.
=> Adding functionality to enforce key uniqueness for labels

gradle/libs.versions.toml, object-store/build.gradle.kts, object-store/src/main/java/org/hypertrace/config/objectstore/DefaultObjectStore.java, object-store/src/main/java/org/hypertrace/config/objectstore/IdentifiedObjectStore.java, object-store/src/test/java/DefaultObjectStoreTest.java, object-store/src/test/java/IdentifiedObjectStoreTest.java, settings.gradle.kts
Config services generally add an abstraction layer over the generic config rpc service, which take a very repetitive form - either for identified many-object config, or a single tenant-scoped config. Reusable abstractions for both are added here.
Added UTs
=> refactor: add object store abstractions

object-store/build.gradle.kts, object-store/src/main/java/org/hypertrace/config/objectstore/ContextuallyIdentifiedObjectStore.java, object-store/src/main/java/org/hypertrace/config/objectstore/DefaultObjectStore.java, object-store/src/main/java/org/hypertrace/config/objectstore/IdentifiedObjectStore.java, object-store/src/test/java/org/hypertrace/config/objectstore/ContextuallyIdentifiedObjectStoreTest.java, object-store/src/test/java/org/hypertrace/config/objectstore/DefaultObjectStoreTest.java, object-store/src/test/java/org/hypertrace/config/objectstore/IdentifiedObjectStoreTest.java
Extract notification methods from IdentifiedObjectStore to be able to override sending notifications.
=> Extract notification methods in identified object store

config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigDocumentKey.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java
Removing version from document store key. Using static "latest" instead. This will ensure only latest version is maintained in the document store. The version history is published by config change events, and can be potentially captured in audit logs.
=> Removing version from document store key

gradle/libs.versions.toml, labels-config-service-impl/build.gradle.kts, labels-config-service-impl/src/main/java/org/hypertrace/label/config/service/LabelsConfigServiceImpl.java
Rather than using an in-memory lock, which prevents horizontal scaling, we're changing the label getOrCreate method here to retry. In conjunction with a separate change to add a unique constraint on the key, this should result in the lock being unnecessary. Concurrent calls may result in an error in the scenario where a label was checked for existence - returned false, then attempted to create and was created in the lag time. In this scenario, we attempt the method again under the assumption the initial read call will work the second time. If we can neither get nor create after two attempts, we give up. In no scenario do we ever end up with duplicates.
TODO
=> refactor: replace lock with unique constraint

config-service-factory/src/main/java/org/hypertrace/config/service/ConfigServiceFactory.java, span-processing-config-service-api/src/main/proto/org/hypertrace/span/processing/config/service/v1/span_processing_config_service.proto, span-processing-config-service-impl/build.gradle.kts, span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceFactory.java, span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceImpl.java, span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceModule.java, span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceImplTest.java, span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceModuleTest.java
This PR adds support for defining system level exclude span rules and overriding(enabling/disabling) them at a tenant level.
Added new unit tests for all new code, and ran all the existing unit tests.
=> feat(system-level-exclusion-rules): system level exclude span rules

span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/validation/SpanProcessingConfigRequestValidator.java, span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/validation/SpanProcessingRequestValidatorTest.java
This PR adds validation for creation of system exclude span rule(deny it). 
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally.
=> fix: add request validation for creation of system exclude rule

span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/apinamingrules/DefaultApiNamingRulesManager.java
This PR contains a fix to optimise bulk creation of api spec based naming rules.
Verified the success of unit tests.
=> fix: Optimise bulk creation of api spec based naming rules

config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/MockGenericConfigService.java
This PR fixes a bug in mockDelete. While we default to default config context if there is no config context while removing an item, we do not do so while verifying if the item is present just before it. This is resulting in a false `NOT_FOUND` error in case of context being absent.
=> fix: default config context in mockDelete

config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java, config-service/build.gradle.kts, config-service/src/integrationTest/java/org/hypertrace/config/service/ConfigServiceIntegrationTest.java, gradle/libs.versions.toml
This PR refactors upsertAllConfigs API impl to use bulk upsert document store method
Added unit tests and integration test to successfully verify the changes
=> chore: use document store bulk upsert

config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java
This PR fixes a bug in the query filter. When we provide no configs to bulk update, the query filter default to an empty OR. This fetches all the configs throughout. We set a limit on the query response to 0 in such cases. But a limit of 0 on mongo is equivalent to no limit.  On update, all these are being set to null as it can't find the values to assign to it as they are not part of the request. 
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally.
=> fix: query filter bug

config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java
This PR adds a check to disallow providing empty config list to bulk upsert.
=> fix: disallow empty providing config list to bulk upsert 

config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/MockGenericConfigService.java, object-store/src/main/java/org/hypertrace/config/objectstore/DeletedContextualConfigObjectImpl.java
This PR adds mock delete all method.
=> chore: add mock deleteAll

helm/templates/config-service-config.yaml, helm/values.yaml, partitioner-config-service-impl/src/main/java/org/hypertrace/partitioner/config/service/PartitionerConfigServiceModule.java, partitioner-config-service-impl/src/main/java/org/hypertrace/partitioner/config/service/PartitionerConfigServiceRequestValidator.java, partitioner-config-service-impl/src/main/java/org/hypertrace/partitioner/config/service/store/PartitionerProfilesDocumentStore.java, partitioner-config-service-impl/src/test/java/org/hypertrace/partitioner/config/service/PartitionerConfigServiceRequestValidatorTest.java
Adding support to create default partitioner profiles if they don't exist on service start up 
=> Add support for default profiles creation for partitioner config service

span-processing-utils/src/main/java/org/hypertrace/config/span/processing/utils/SpanFilterMatcher.java
=> Remove exception logging from error log

alerting-config-service-api/build.gradle.kts, config-proto-converter/build.gradle.kts, config-service-api/build.gradle.kts, config-service-factory/src/main/java/org/hypertrace/config/service/ConfigServiceFactory.java, gradle/libs.versions.toml, label-application-rule-config-service-api/build.gradle.kts, labels-config-service-api/build.gradle.kts, notification-channel-config-service-api/build.gradle.kts, notification-channel-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceImpl.java, notification-channel-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceRequestValidator.java, notification-channel-config-service-impl/src/test/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceImplTest.java, notification-channel-config-service-impl/src/test/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceRequestValidatorTest.java, notification-channel-config-service-impl/src/test/resources/application.conf, notification-rule-config-service-api/build.gradle.kts, partitioner-config-service-api/build.gradle.kts, spaces-config-service-api/build.gradle.kts, span-processing-config-service-api/build.gradle.kts
Add domain exclusion config for notification channel config service. This config will fail the creation/update of notification channels if it contains exclusion domains.
=> Add webhook domain exclusion config for notification channels

build.gradle.kts
We don't want PR to get blocked when dependency check is unable to download
- [-] I have added tests that prove my fix is effective or that my feature works
=> Warning on remote errors in dependency check

config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, notification-channel-config-service-api/src/main/proto/org/hypertrace/notification/config/service/v1/notification_channel.proto, notification-channel-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationChannelConfigServiceRequestValidator.java
Added support for syslog server integration in notification channel config.
=> feat: added syslog support in notification channel

.github/workflows/codeql-analysis.yml
codeql workflow was not getting tags which caused it to mismatch with locks.
=> ci: update codeql to get tags

label-application-rule-config-service-api/src/main/proto/org/hypertrace/label/application/rule/config/service/v1/label_application_rule.proto, label-application-rule-config-service-impl/src/main/java/org/hypertrace/label/application/rule/config/service/LabelApplicationRuleValidatorImpl.java, label-application-rule-config-service-impl/src/test/java/org/hypertrace/label/application/rule/config/service/LabelApplicationRuleValidatorTest.java
=> Add not exists, not equals and not matches regex operator support for label application rules

span-processing-config-service-api/src/main/proto/org/hypertrace/span/processing/config/service/v1/span_filter.proto, span-processing-config-service-impl/src/test/java/org/hypertrace/span/processing/config/service/SpanProcessingConfigServiceImplTest.java
While creating exclusion rules, having “URL path” as a first class field would be very helpful to have exclusion rules only on the “URL path”, and not query parameters/anchor tags
Say, we want to exclude static URLs (.html, .css etc). Basically, excluding URLs ending with a certain extension. The regex for exclusion rule becomes clumsy and inaccurate on “full URLs”, since it could have query parameters
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) …
=> Expose URL_PATH in exclusion rules

notification-rule-config-service-api/src/main/proto/org/hypertrace/notification/config/service/v1/notification_rule.proto, notification-rule-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceImpl.java, notification-rule-config-service-impl/src/main/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceRequestValidator.java, notification-rule-config-service-impl/src/test/java/org/hypertrace/notification/config/service/NotificationRuleConfigServiceImplTest.java
For non-streaming notification. Particularly for integrations supporting a batched type of notification.
=> Changes in Notification rule to allow types

.github/workflows/codeql-analysis.yml, .github/workflows/merge-publish.yml, .github/workflows/pr-build.yml, .github/workflows/pr-test.yml, .github/workflows/publish.yml, owasp-suppressions.xml, validation-utils/src/main/java/org/hypertrace/config/validation/GrpcValidatorUtils.java
Add a validation util that detects whether an optional field has been explicitly assigned. Our existing util looks if a field resolves to its default value which means it will flag optional fields assigned to their default value - sometimes that's desirable, but sometimes it's not.
Did a bit of housekeeping with old suppressions and versions while I was in here.
=> chore: add new validation util and a bit of housekeeping

config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigDocument.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigStore.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/ConfigDocumentTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java
=> Store user details in config objects in mongo

label-application-rule-config-service-api/src/main/proto/org/hypertrace/label/application/rule/config/service/v1/label_application_rule.proto, label-application-rule-config-service-impl/src/main/java/org/hypertrace/label/application/rule/config/service/LabelApplicationRuleValidatorImpl.java, validation-utils/src/main/java/org/hypertrace/config/validation/RegexValidator.java
Defined regex capture to perform operation on attribute value like substring etc.
=> chore: add regex capture to label application rule

span-processing-config-service-api/src/main/proto/org/hypertrace/span/processing/config/service/v1/span_processing_config_service.proto
Reverts hypertrace/config-service#216
=> Revert "chore | Proto changes for adding evaluation targets for each exclude span rule"

config-service-change-event-api/src/main/proto/org/hypertrace/config/change/event/v1/config_change_event_value.proto, config-service-change-event-generator/src/main/java/org/hypertrace/config/service/change/event/impl/ConfigChangeEventGeneratorImpl.java, config-service-change-event-generator/src/test/java/org/hypertrace/config/service/change/event/impl/ConfigChangeEventGeneratorImplTest.java
Capture user email when generating change events. This is required to filter out the names of traceable employees on customers' activity logs.
=> Add email in config_change_event_value.proto

config-service-impl/build.gradle.kts, config-service-impl/src/main/java/org/hypertrace/config/service/store/FilterBuilder.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/FilterBuilderTest.java, object-store/src/main/java/org/hypertrace/config/objectstore/IdentifiedObjectStore.java
=> ENG-48723: Filter builder fix and object store changes

span-processing-config-service-impl/src/main/java/org/hypertrace/span/processing/config/service/validation/SpanProcessingConfigRequestValidator.java, span-processing-utils/src/main/java/org/hypertrace/config/span/processing/utils/SpanFilterMatcher.java
=> Fix environment and service name match for unary span filter expression

.github/workflows/pr-test.yml, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java
=> Revert document store createOrReplace api

config-service-api/src/main/proto/org/hypertrace/config/service/v1/config_service.proto, config-service-impl/src/main/java/org/hypertrace/config/service/ConfigServiceGrpcImpl.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConfigStore.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/ConstantExpressionConverter.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/main/java/org/hypertrace/config/service/store/FilterExpressionBuilder.java, config-service-impl/src/test/java/org/hypertrace/config/service/ConfigServiceGrpcImplTest.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java
Add support for Filtering, pagination and sorting in Config Service GetAllConfigsAPI
=> Filtering pagination support impl

config-service-impl/src/main/java/org/hypertrace/config/service/store/DocumentConfigStore.java, config-service-impl/src/test/java/org/hypertrace/config/service/store/DocumentConfigStoreTest.java
Sorting on configVersion no longer required, so removing it.
Combination of tenant-id, reosurce-namespace, resource-name and context are unique
=> Removed sorting on configVersion

config-service-api/src/testFixtures/java/org/hypertrace/config/service/test/MockGenericConfigService.java
Added a mock api for GetAllWithFilter api which has filtering support.
=> Added mockAPI for getAllWithFilter

config-service-impl/src/main/java/org/hypertrace/config/service/store/FilterExpressionBuilder.java
Updated `FilterExpressionBuilder` to account for default or `null` value being passed in the Relational Expression when the operators are `EXISTS` or `NOT_EXISTS`.
=> Fix: Updated Filter Converter to account for EXISTS and NOT_EXISTS Filters
